### ISSUE TITLE
Surface Laptop: qzed's script is randomly broken

### ISSUE THREAD

**Issue by recolic** [calvous/Surface-Fakedev#2]
qzed's script works for Surface Laptop after modifications below:

- use /dev/ttyS0 rather than /dev/ttyS4

- use baudrate 1843200 rather than 3000000

But this script doesn't.

### TODO: I'll open my Surface and attach more information soon

**Comment by recolic** [comment]
It works for Surface Laptop now... Sorry to bother.

**Comment by calvous** [comment]
hi @recolic 
@qzed wrote the script for surface 5 series devices. Older ones could not be testet. I have updated my readme.md with some instructions. Your output would be very valuable.

**Comment by recolic** [comment]
@calvous What can I do for this project? I'm using Surface Laptop 2(bought at Aug 2018). This script works well after modifying the baudrate...

**Comment by qzed** [comment]
@calvous The laptop is actually a 5th generation device, but for some reason the baud rate is different (and interestingly also the respective serial port, might be due to slight hardware changes). You could maybe try and replace the baud rate based on some user input or try detect the system based on dmidecode, as Jake is doing in his setup script.

**Comment by calvous** [comment]
> @calvous What can I do for this project? I'm using Surface Laptop 2(bought at Aug 2018). This script works well after modifying the baudrate...

I am sorry about that but this was not expected. And this is why your output is important. Glad it works for you now :+1:

**Comment by calvous** [comment]
@qzed 
> @calvous The laptop is actually a 5th generation device, but for some reason the baud rate is different (and interestingly also the respective serial port, might be due to slight hardware changes). You could maybe try and replace the baud rate based on some user input or try detect the system based on dmidecode, as Jake is doing in his setup script.

I have on my Surface Pro 1796 Manjaro (ARCH) and Ubuntu. Manjaro recognizes the device on ttyS0 while Ubuntu does it on ttyS4. So it is possible that different device names are not hardware related. Most of the users here have the ubuntu surface kernel while I have to compile it for myself. Other than that I am mostly running on 4.14 and 4.18 w/o jakedays patches (don't care about touchscreen) and your script still works.

**Comment by qzed** [comment]
Oh, right, sorry. You're right.

**Comment by recolic** [comment]
I reinstalled my Arch Linux just now and everything is broken... All scripts (qzed's, every commit in this repo) are not working now... Currently looking for the reason and I'll reopen this issue once I've found something

```
# I'm using baudrate 1843200 and ttyS0
ww@WWPC ~/t/Surface-Fakedev> sudo python mshw0084-rqst.py bat1.pretty
received: aa55400000017dfaffff
received: aa5580140062bf8a
received: 80080002000100030100312a00000000000000002fc5
Traceback (most recent call last):
  File "mshw0084-rqst.py", line 408, in <module>
    main()
  File "mshw0084-rqst.py", line 393, in main
    res = cmd.run(dev, cnt)
  File "mshw0084-rqst.py", line 305, in run
    bix = self.bix.run(dev, cnt)
  File "mshw0084-rqst.py", line 212, in run
    seq, pld, rem = self._read_msg(dev, cnt.cnt)
  File "mshw0084-rqst.py", line 149, in _read_msg
    assert msg[0:8] == bytes([0x80, self.rtc, 0x00, 0x01, self.riid, cnt_lo, cnt_hi, self.rcid])
AssertionError
```

Run it another time after reboot:
```
ww@WWPC ~/t/Surface-Fakedev> sudo python mshw0084-rqst.py bat1.pretty
received: aa55400000033fdaffff
received: aa55801400f5e179
received: 800800020001000301002a00000000000000000059e2
Traceback (most recent call last):
  File "mshw0084-rqst.py", line 408, in <module>
...
```

### Update

It works after I slept for a night.

```
# Reboot
ww@WWPC ~/t/Surface-Fakedev> sudo python mshw0084-rqst.py bat1.pretty
[sudo] password for ww: 
received: aa5504000000314effff
received: aa5540000005f9baffff
received: aa55807f003537cb
received: 8002000101050002000000000090b0000096b9000001000000931d00007c1a00004c0500000f000000e8030000ffffffffffffffffe8030000e80300000a0000000a0000004d313030353932320000000000000000000000000030303335303432373436004c494f4e0044594e000000000000000000000000000000000000c255
ignored MSG: aa55807f003537cb8002000101050002000000000090b0000096b9000001000000931d00007c1a00004c0500000f000000e8030000ffffffffffffffffe8030000e80300000a0000000a0000004d313030353932320000000000000000000000000030303335303432373436004c494f4e0044594e000000000000000000000000000000000000c255
received: aa55400000069a8affff
received: aa5580180036afe5
received: 8002000101060003020000003247000050a00000fc210000dc2f
ignored MSG: aa5580180036afe58002000101060003020000003247000050a00000fc210000dc2f

{'Percentage': '86%',
 'Remaing ': '2.25h',
 'State': 'Charging',
 'Voltage': '8.7V'}
```

**Comment by recolic** [comment]
The `mshw0084-rqst.py` is still randomly broken (broken in about 30% time) and I can not reproduce it easily. So I'm reopening this issue.
Here's the log of the reproducing...... Thanks a lot for your help!
```
ww@WWPC ~/t/Surface-Fakedev> sudo python mshw0084-rqst.py bat1.pretty
received: aa5540000007bb9affff
received: aa55801400760ad8
received: 80080002000100030122000000000000000000005c45
Traceback (most recent call last):
  File "mshw0084-rqst.py", line 408, in <module>
    main()
  File "mshw0084-rqst.py", line 393, in main
    res = cmd.run(dev, cnt)
  File "mshw0084-rqst.py", line 305, in run
    bix = self.bix.run(dev, cnt)
  File "mshw0084-rqst.py", line 212, in run
    seq, pld, rem = self._read_msg(dev, cnt.cnt)
  File "mshw0084-rqst.py", line 149, in _read_msg
    assert msg[0:8] == bytes([0x80, self.rtc, 0x00, 0x01, self.riid, cnt_lo, cnt_hi, self.rcid])
AssertionError
```

My script is attached here: https://recolic.net/tmp/mshw0084-rqst.py

**Comment by qzed** [comment]
That's interesting. The response does not look like something I've seen before, it's definitely not a response for the `BATx._BIX` command.
```
80 |08| 00 02 |00| 01 00 |03| |01 22 00 00 00 00 00 00 00 00 00 00| 5c 45
    --     --      -----
```
The checksum is valid, so it's definitely a valid response. I've underlined the most interesting parts. The `RTC` (first byte marked with `|..|`) is definitely odd, I've never seen `08` on that before. The same with the `02` (I've only seen `01` in that place), maybe this could be some revision ID or another indicator to the purpose of this message. The counter that is used to match request and response is identically interesting (third underlined bytes), as it is fixed to `0x0001`. The last one could just be random, but I think that this might be some sort of event message sent/initiated by the controller.

Are they always the same?

To fix this you could, for now, change the assertion so that it just discards the response in question and re-starts parsing after that.

**Comment by recolic** [comment]
@qzed Currently I can not reproduce it easily. But I've collected some responses in the history:

```
80080002000100030100312a00000000000000002fc5
800800020001000301002a00000000000000000059e2
80080002000100030122000000000000000000005c45
```

I'll try changing the assertion on the next successful reproduction...

**Comment by calvous** [comment]
@recolic 
First of all I am sorry because I just missed the notification that this issue had been reopened. 
I saw you run the script as ```sudo python ...```
I do not know what that does but it should not be run like that because the environment is sourced inside the script and demands python3. Further on I have uploaded new files but this is probably not reflected in this git (I am at no means a pro with github). Sorry again for the trouble. It is all in the README. However, @qzed has meanwhile provided an acpi_notify module that just works great and therefore renders this workaround here obsolete. Please let me know if you still need assistance with this stuff here or if I can be of any help to get qzeds module working for you. Otherwise I would like to close this issue here.

**Comment by recolic** [comment]
@calvous Thanks a lot for your help. I'll test the acpi_notify module. Please leave this issue open before I've finished my testing....

**Comment by recolic** [comment]
lose my surface laptop...... unable to test
