### ISSUE TITLE
TypeError: invalid file: PosixPath('/var/log/.counters.json')

### ISSUE THREAD

**Issue by calvous** [calvous/Surface-Fakedev#3]
https://github.com/jakeday/linux-surface/issues/28#issuecomment-429801630

**Comment by calvous** [comment]
This could be because the file ".counters.json" cannot be created. Pleas check your filesystem for the file existing:
```
ls -l /var/log/.counters.json
```
If it is not there create it
```
sudo touch /var/log/.counters.json
sudo chmod 666 /var/log/.counters.json
```

**Comment by calvous** [comment]
Oh my dear, I am the devil. Bet

**Comment by srickardsson** [comment]
There was no such file. After i created it, the error message became much smaller. Now we have this to work with: 

Traceback (most recent call last):
  File "./power-status.py", line 446, in <module>
    main()
  File "./power-status.py", line 427, in main
    cnt = Counters.load()
  File "./power-status.py", line 49, in load
    with open(Counters.PATH) as fd:
TypeError: invalid file: PosixPath('/var/log/.counters.json')

**Comment by calvous** [comment]
sry, closed it by accident

**Comment by srickardsson** [comment]
No problem! Do you think this will be possible to solve, or should I just wait for the kernel update when this will be fixed?

**Comment by calvous** [comment]
Oh dear, what have I done? I am not sure what happens there but try this:
Edit the power-status.py file in line 44
```
PATH = Path(__file__).parent / '/var/log/.counters.json'
```
change it to
```
PATH = Path(__file__).parent / '.counters.json'
```
try again. Also download the original from qzed's repository https://gist.github.com/qzed/01a93568efb863f1b7887f0f375c03fc
Run it as root with bat1.pretty or bat1._bix or bat1._sta
If it does not work either you need to contact qzed.

**Comment by srickardsson** [comment]
That did not work either. I think i will wait untill the kernel update. Thank you anyways for your time! Appreciate it very much!

**Comment by calvous** [comment]
you are very welcome. Maybe it is just the kernel version.

**Comment by calvous** [comment]
@schimapan 
One last thing. The gnome-extension does not work with only one Battery. I you have only one battery you could do this
```
sudo ln -s /etc/fakedev/power_supply/BAT1/uevent /etc/fakedev/power_supply/BAT2/uevent
```

**Comment by srickardsson** [comment]
I do have 2 batteries, one in the base and one in the screen.

**Comment by calvous** [comment]
@schimapan 
just got a note from @qzed https://github.com/calvous/Surface-Fakedev/issues/1#issuecomment-430020501
try the dmesg command and see what it returns. It shows this on my box
```
$ dmesg|grep ttyS
[    3.704490] dw-apb-uart.2: ttyS0 at MMIO 0xa1336000 (irq = 20, base_baud = 3000000) is a 16550A
```
You can than use the tty name and baud rate and replace it in "power-status.py" (line 15 and 16)

**Comment by qzed** [comment]
@schimapan what python version are you using? According to [stackoverflow](https://stackoverflow.com/questions/42694112/when-using-pathlib-getting-error-typeerror-invalid-file-posixpathexample-t) this could be due to python version <= 3.5.

@calvous Not sure if you want to replace `Counters.PATH` with a fixed string instead of using `pathlib.Path`, that would make it a bit more backward-compatible (with respect to the above link), especially if you know where the file will be. I only used the `Path(__file__).parent` to make sure the counters file is relative to the script, but looking back at it it would probably have been a better idea to put that file somewhere in `/tmp`, the counters do not need to be kept over re-boots.

**Comment by srickardsson** [comment]
@calvous The command is returning his for me: 
$ dmesg | grep ttyS
[    5.539611] dw-apb-uart.4: ttyS4 at MMIO 0xc2748000 (irq = 20, base_baud = 3000000) is a 16550A
(Which i have changed ttys0 to ttys4) but i still get the error message when running the sudo ./power-status.py bat1.uevent command.

**Comment by srickardsson** [comment]
@qzed It looks like i have both python3 and python3.5. Should i try to remove the 3.5 version then?

**Comment by qzed** [comment]
@schimapan In that case `python3` should be an alias for `python3.5`, so you should have python 3.5. You can try to change the `Command.PATH` vairable to a string, that should do the trick (e.g. `/tmp/surface-ec-counters.json`).

**Comment by srickardsson** [comment]
@qzed Sorry but where should i do that? I am very new to all this so please bare with my noob questions.

**Comment by srickardsson** [comment]
I tried removing python3.5 and alot of other stuff got removed with that. And now it seems like python3.5 i back after i installed everything again. And now my error message when i run the ./power-status.py bat1.uevent command is:

Traceback (most recent call last):
  File "./power-status.py", line 446, in <module>
    main()
  File "./power-status.py", line 427, in main
    cnt = Counters.load()
  File "./power-status.py", line 49, in load
    with open(Counters.PATH) as fd:
TypeError: invalid file: PosixPath('/var/log/.counters.json')

**Comment by qzed** [comment]
@schimapan Just change [this](https://github.com/calvous/Surface-Fakedev/blob/47069e4e9edf998940c34f40ff642f164d13af8b/power-status.template#L44) line to something like
```
PATH = '/tmp/surface-ec-counters.json'
```

**Comment by srickardsson** [comment]
@qzed Looks like the error message just changed to line 48 instead of line 49 when i changed that line.

Traceback (most recent call last):
  File "./power-status.py", line 446, in <module>
    main()
  File "./power-status.py", line 427, in main
    cnt = Counters.load()
  File "./power-status.py", line 48, in load
    if Counters.PATH.is_file():
AttributeError: 'str' object has no attribute 'is_file'

**Comment by qzed** [comment]
@schimapan oh yeah right, sorry, totally forgot about the check on that line. You also have to replace [that](https://github.com/calvous/Surface-Fakedev/blob/47069e4e9edf998940c34f40ff642f164d13af8b/power-status.template#L48) line with
```
os.path.isfile(Counters.PATH) 
```
and also add an import at the beginning of the file
```
import os.path
```

**Comment by schimapan** [comment]
@qzed Thanks! Now it seems to work!

**Comment by srickardsson** [comment]
@qzed Thanks! Now it seems to be working!

POWER_SUPPLY_VOLTAGE_MIN_DESIGN=7500
POWER_SUPPLY_VOLTAGE_NOW=8479
POWER_SUPPLY_POWER_NOW=2492
POWER_SUPPLY_ENERGY_FULL_DESIGN=18000
POWER_SUPPLY_ENERGY_FULL=17430
POWER_SUPPLY_ENERGY_NOW=16710
POWER_SUPPLY_ENERGY_LOW=0
POWER_SUPPLY_CAPACITY=95
POWER_SUPPLY_MODEL_NAME=M1030911
POWER_SUPPLY_MANUFACTURER=SMP
POWER_SUPPLY_SERIAL_NUMBER=8181944745
POWER_SUPPLY_NAME=BAT1

Now the only problem is that i dont have any battery indicator on top of the screen. I assume that is because i am running elementary os. Is there any way to make it work on EOS or should i just use that command whenever i want to know the battery percentage?

**Comment by qzed** [comment]
Nice! I cant help you with the rest though, sorry.

**Comment by srickardsson** [comment]
@qzed Okay, i understand. Thank you so much for your time!

**Comment by calvous** [comment]
@qzed 
I have changed it back to the original. I was just not sure if it is good to have a config file in /usr/bin (that's where the cronjob starts the script)

**Comment by calvous** [comment]
@schimapan 
If you are running a gnome like DE get the files from @thmichel here: https://github.com/jakeday/linux-surface/issues/28#issuecomment-428876786
Also make sure you put all the modifications you made in power-status.py into the /usr/bin/power-status.py

**Comment by qzed** [comment]
@calvous Yeah, I agree. Putting the counters file in `/bin/...` is probably not the best idea. As I already said, you could put it somewhere in `/tmp/...`, I think that should be the proper place.

**Comment by calvous** [comment]
pls try the new version.
